In [15]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [2]:
#Carrega o dataset com os dados para o treinamento e validacao
airlines_dataset = pd.read_csv("../../data/Airlines.csv", encoding="utf-8")

In [3]:
# Visualizando os primeiros dados da tabela.
airlines_dataset.head(10)

id Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0   1      CO     269         SFO       IAH          3    15     205      1
1   2      US    1558         PHX       CLT          3    15     222      1
2   3      AA    2400         LAX       DFW          3    20     165      1
3   4      AA    2466         SFO       DFW          3    20     195      1
4   5      AS     108         ANC       SEA          3    30     202      0
5   6      CO    1094         LAX       IAH          3    30     181      1
6   7      DL    1768         LAX       MSP          3    30     220      0
7   8      DL    2722         PHX       DTW          3    30     228      0
8   9      DL    2606         SFO       MSP          3    35     216      1
9  10      AA    2538         LAS       ORD          3    40     200      1

In [4]:
airlines_dataset['Airline'], airlines_mapping = pd.factorize(airlines_dataset['Airline'])

In [5]:
airlines_dataset['AirportFrom'], airlines_mapping = pd.factorize(airlines_dataset['AirportFrom'])

In [6]:
airlines_dataset['AirportTo'], airlines_mapping = pd.factorize(airlines_dataset['AirportTo'])

In [8]:
airlines_dataset.head(10)

id  Airline  Flight  AirportFrom  AirportTo  DayOfWeek  Time  Length  Delay
0   1        0     269            0          0          3    15     205      1
1   2        1    1558            1          1          3    15     222      1
2   3        2    2400            2          2          3    20     165      1
3   4        2    2466            0          2          3    20     195      1
4   5        3     108            3          3          3    30     202      0
5   6        0    1094            2          0          3    30     181      1
6   7        4    1768            2          4          3    30     220      0
7   8        4    2722            1          5          3    30     228      0
8   9        4    2606            0          4          3    35     216      1
9  10        2    2538            4          6          3    40     200      1

In [9]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(airlines_dataset[['Airline', 'Flight', 'AirportFrom', 'AirportTo', 'DayOfWeek', 'Time', 'Length']])
#Definição do atributo de classificacao
data_classif = np.array(airlines_dataset['Delay'])

In [10]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [11]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[  13   94    1 ...    5  859  128]
 [   7 6861    2 ...    2 1192   70]
 [   7 4784    5 ...    5 1185  162]
 ...
 [  17  938   30 ...    4  755  320]
 [   4 2143   14 ...    2  500  159]
 [   7 4656   25 ...    7  860  110]]
Conjunto de Validacao
[[   7 4548    5 ...    2 1015  154]
 [  17 1235   30 ...    2  770  280]
 [   8 3797  130 ...    1  920   59]
 ...
 [  15  183   88 ...    1  360  123]
 [  17 2038  130 ...    4 1105  105]
 [   7 6858    6 ...    1  934  137]]
-----------------------


In [12]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [18]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.6049453343503687
Na Base de Treinamento


In [17]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste e ou Validação")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.6043135679634151
na Base de Teste e ou Validação


In [16]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[29743 42237]
 [21791 68044]]

Classification Report
              precision    recall  f1-score   support

           1       0.58      0.41      0.48     71980
           0       0.62      0.76      0.68     89835

    accuracy                           0.60    161815
   macro avg       0.60      0.59      0.58    161815
weighted avg       0.60      0.60      0.59    161815

