In [1]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [3]:
#Carrega o dataset com os dados para o treinamento e validacao
employee_data = pd.read_csv("../data/Employee.csv", encoding="utf-8")

In [4]:
employee_data.tail(10)

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4643  Bachelors         2013  Bangalore            3   31  Female          No   
4644  Bachelors         2015       Pune            3   32  Female         Yes   
4645    Masters         2017       Pune            2   31  Female          No   
4646  Bachelors         2013  Bangalore            3   25  Female          No   
4647  Bachelors         2016       Pune            3   30    Male          No   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
4643                          5           0  
4644                          1           1  
4645                          2           0  
4646                          3           0  
4647                          2           0  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0

In [9]:
employee_data['Gender'] = employee_data['Gender'].replace({'Male': 1, 'Female': 0})

In [10]:
employee_data['EverBenched'] = employee_data['EverBenched'].replace({'No': 0, 'Yes': 1})

In [11]:
employee_data['City'] = employee_data['City'].replace({'Bangalore': 0, 'Pune': 1, 'New Delhi': 2})

In [12]:
employee_data['Education'] = employee_data['Education'].replace({'Bachelors': 0, 'Masters': 1, 'PHD': 2})

In [13]:
employee_data.tail(10)

Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
4643          0         2013     0            3   31       0            0   
4644          0         2015     1            3   32       0            1   
4645          1         2017     1            2   31       0            0   
4646          0         2013     0            3   25       0            0   
4647          0         2016     1            3   30       1            0   
4648          0         2013     0            3   26       0            0   
4649          1         2013     1            2   37       1            0   
4650          1         2018     2            3   27       1            0   
4651          0         2012     0            3   30       1            1   
4652          0         2015     0            3   33       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
4643                          5           0  
4644                          1           1  
4645                          2           0  
4646                          3           0  
4647                          2           0  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0

In [14]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(employee_data[['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender', 'EverBenched', 'ExperienceInCurrentDomain']])
#Definição do atributo de classificacao
data_classif = np.array(employee_data['LeaveOrNot'])

In [15]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [16]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[   1 2018    2 ...    0    0    5]
 [   0 2015    2 ...    0    0    0]
 [   0 2017    2 ...    1    0    4]
 ...
 [   0 2015    2 ...    1    0    0]
 [   0 2015    0 ...    1    0    5]
 [   0 2017    1 ...    1    0    4]]
Conjunto de Validacao
[[   1 2017    2 ...    0    0    5]
 [   0 2012    0 ...    0    0    5]
 [   0 2014    1 ...    1    0    1]
 ...
 [   0 2018    2 ...    0    0    0]
 [   2 2013    2 ...    1    0    2]
 [   0 2013    0 ...    1    0    1]]
-----------------------


In [17]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [18]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.65704636168253
Na Base de Treinamento


In [19]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste e ou Validação")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.6396848137535817
na Base de Teste e ou Validação


In [20]:
from sklearn import metrics

In [21]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(metrics.confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(metrics.classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[191 299]
 [204 702]]

Classification Report
              precision    recall  f1-score   support

           1       0.48      0.39      0.43       490
           0       0.70      0.77      0.74       906

    accuracy                           0.64      1396
   macro avg       0.59      0.58      0.58      1396
weighted avg       0.62      0.64      0.63      1396

