In [1]:
#Conjunto de importacoes
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
#Carrega o dataset com os dados para o treinamento e validacao
employee_data = pd.read_csv("../../data/Employee.csv", encoding="utf-8")

In [3]:
employee_data.head(10)

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   
5  Bachelors         2016  Bangalore            3   22    Male          No   
6  Bachelors         2015  New Delhi            3   38    Male          No   
7  Bachelors         2016  Bangalore            3   34  Female          No   
8  Bachelors         2016       Pune            3   23    Male          No   
9    Masters         2017  New Delhi            2   37    Male          No   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1  
5                          0           0  
6                          0           0  
7                          2           1  
8                          1           0  
9                          2           0

In [5]:
employee_data['Gender'] = employee_data['Gender'].replace({'Male': 1, 'Female': 0})

In [7]:
employee_data['EverBenched'] = employee_data['EverBenched'].replace({'No': 0, 'Yes': 1})

In [9]:
employee_data['City'] = employee_data['City'].replace({'Bangalore': 0, 'Pune': 1, 'New Delhi': 2})

In [12]:
employee_data['Education'] = employee_data['Education'].replace({'Bachelors': 0, 'Masters': 1, 'PHD': 2})

In [13]:
employee_data.head(10)

Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
0          0         2017     0            3   34       1            0   
1          0         2013     1            1   28       0            0   
2          0         2014     2            3   38       0            0   
3          1         2016     0            3   27       1            0   
4          1         2017     1            3   24       1            1   
5          0         2016     0            3   22       1            0   
6          0         2015     2            3   38       1            0   
7          0         2016     0            3   34       0            0   
8          0         2016     1            3   23       1            0   
9          1         2017     2            2   37       1            0   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1  
5                          0           0  
6                          0           0  
7                          2           1  
8                          1           0  
9                          2           0

In [14]:
#Definição dos atributos que deverao ser treinados para gerar o modelo de classificacao
data_treino = np.array(employee_data[['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender', 'EverBenched', 'ExperienceInCurrentDomain']])
#Definição do atributo de classificacao
data_classif = np.array(employee_data['LeaveOrNot'])

In [15]:
#Definição dos conjuntos de treinamento e validação
x_treino, x_val, y_treino, y_val = train_test_split(data_treino, data_classif, test_size=0.30)

In [16]:
#Apresentacao dos dados selecionados para o conjunto de treinamento e validacao
print("-----------------------")
print("Conjunto de Treinamento")
print(x_treino)
print("Conjunto de Validacao")
print(x_val)
print("-----------------------")

-----------------------
Conjunto de Treinamento
[[   1 2012    2 ...    1    0    4]
 [   0 2017    0 ...    0    0    5]
 [   0 2016    1 ...    1    0    2]
 ...
 [   1 2014    2 ...    1    0    5]
 [   1 2017    0 ...    1    0    4]
 [   0 2018    0 ...    1    0    1]]
Conjunto de Validacao
[[   0 2014    0 ...    1    0    2]
 [   0 2015    2 ...    0    0    1]
 [   0 2016    0 ...    1    0    4]
 ...
 [   0 2014    0 ...    1    0    1]
 [   0 2016    2 ...    0    0    1]
 [   0 2017    0 ...    1    0    4]]
-----------------------


In [17]:
#Treinamento do modelo com os dados atribuidos ao conjunto de treinamento
modelo_NB = GaussianNB()
modelo_NB.fit(x_treino, y_treino)

GaussianNB()

In [18]:
#Predição e acurácia para o conjunto de treinamento
print("Predicao para o conjunto de treinamento")
y_pred_treino = modelo_NB.predict(x_treino)
print("Acuracia para o conjunto de treinamento")
print(accuracy_score(y_treino, y_pred_treino))
print("Na Base de Treinamento")

Predicao para o conjunto de treinamento
Acuracia para o conjunto de treinamento
0.6868283696653362
Na Base de Treinamento


In [19]:
#Predição e acurácia para o conjunto de validação
print("Predicao para o conjunto de validacao")
y_pred_val = modelo_NB.predict(x_val)
print("Acuracia para o conjunto de validacao")
print(accuracy_score(y_val, y_pred_val))
print("na Base de Teste e ou Validação")

Predicao para o conjunto de validacao
Acuracia para o conjunto de validacao
0.6898280802292264
na Base de Teste e ou Validação


In [20]:
# Criando uma Confusion Matrix
print("Confusion Matrix")

print("{0}".format(confusion_matrix(y_val, y_pred_val, labels = [1, 0])))
print("")

print("Classification Report")
print(classification_report(y_val, y_pred_val, labels = [1, 0]))

Confusion Matrix
[[204 280]
 [153 759]]

Classification Report
              precision    recall  f1-score   support

           1       0.57      0.42      0.49       484
           0       0.73      0.83      0.78       912

    accuracy                           0.69      1396
   macro avg       0.65      0.63      0.63      1396
weighted avg       0.68      0.69      0.68      1396

